# Coverage settings for covdbg
# Format version: 1

version: 1
source_root: "."
coverage:
  default:
    files:
      # Select which source files are included in the coverage report.
      #
      # The patterns are glob-style:
      #   - '*'  matches any characters within a single path segment (no directory separators)
      #   - '**' matches across directory boundaries (recursive)
      #
      # Files matched by 'include' are added to the coverage database even if they are
      # not discovered via linked debug info (PDB). If they are never executed, they
      # will appear as 0% coverage (LCOV-like behavior).
      include:
        - "src/**/*.cpp"
        - "src/**/*.h"

      # Exclude specific files or directories from the report.
      # Exclude rules always take precedence over include rules.
      exclude:
        # =====================================================================
        # Windows SDK and Universal CRT (installed paths)
        # "C:/Program Files*/Windows Kits/**"
        # =====================================================================
        - "**/Windows Kits/**"

        # =====================================================================
        # MSVC Toolchain (installed paths)
        # "C:/Program Files*/Microsoft Visual Studio/**/VC/Tools/**"
        # =====================================================================
        - "**/VC/Tools/MSVC/**"

        # =====================================================================
        # MSVC CRT/STL Source (build server paths from PDBs)
        # These patterns match paths embedded in Microsoft's pre-built binaries
        # from their internal build systems (D:\a\_work\1\s\src\...)
        # =====================================================================
        - "**/vctools/crt/**"           # CRT runtime, startup, vcruntime
        - "**/vctools/langapi/**"       # Language API (undname, etc.)
        - "**/stl/inc/**"               # STL headers
        - "**/stl/src/**"               # STL source

        # =====================================================================
        # Universal CRT (UCRT) - minkernel paths from Windows PDBs
        # =====================================================================
        - "**/minkernel/crts/ucrt/**"   # UCRT implementation
        - "**/minkernel/crts/crtw32/**" # Legacy CRT components

        # =====================================================================
        # Windows SDK internals (onecore paths from Windows PDBs)
        # =====================================================================
        - "**/onecore/**"               # OneCore SDK internals

        # =====================================================================
        # External SDK includes embedded in PDBs
        # =====================================================================
        - "**/ExternalAPIs/**"          # External API headers
        - "**/binaries/amd64ret/inc/**" # Binary distribution includes

        # =====================================================================
        # Project-specific exclusions
        # =====================================================================
        # Build dependencies (CMake FetchContent, etc.)
        - "build/**/_deps/**"

        # Test files (exclude from coverage report)
        - "src/**/*Tests.cpp"

    functions:
      # Control which functions are included in function-level coverage.
      #
      # Patterns can be fully qualified names (e.g. Namespace::Class::Method) or
      # wildcard expressions using '*'.
      include:
        - "*"  # Include all functions by default

      # Exclude specific functions (or patterns) from function-level coverage.
      # These are compiler-generated or runtime functions that add noise.
      exclude:
        # MSVC empty global delete (generated by compiler)
        - "__empty_global_delete"

        # CRT startup/initialization functions
        - "__scrt_*"
        - "_RTC_*"
        - "__security_*"
        - "__GSHandler*"
